config/routes.rb
Rails.application.routes.draw do
  resources :parks do
    resources :plants, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/park.rb
class Park < ApplicationRecord
  has_many :plants
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :park
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/parks_controller.rb
class ParksController < ApplicationController
  before_action :set_park, only: %i[ show edit update destroy ]

  # GET /parks or /parks.json
  def index
    @parks = Park.all
  end

  # GET /parks/1 or /parks/1.json
  def show
  end

  # GET /parks/new
  def new
    @park = Park.new
  end

  # GET /parks/1/edit
  def edit
  end

  # POST /parks or /parks.json
  def create
    @park = Park.new(park_params)

    respond_to do |format|
      if @park.save
        format.html { redirect_to @park, notice: "Park was successfully created." }
        format.json { render :show, status: :created, location: @park }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parks/1 or /parks/1.json
  def update
    respond_to do |format|
      if @park.update(park_params)
        format.html { redirect_to @park, notice: "Park was successfully updated." }
        format.json { render :show, status: :ok, location: @park }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @park.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parks/1 or /parks/1.json
  def destroy
    @park.destroy
    respond_to do |format|
      format.html { redirect_to parks_url, notice: "Park was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_park
      @park = Park.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def park_params
      params.require(:park).permit(:name, :banner_url)
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    @plant = Plant.new
    @park = Park.find(params[:park_id])
  end

  def create
    @park = Park.find(params[:park_id])
    @plant = Plant.new(plant_params)
    @plant.park = @park
    if @plant.save
      redirect_to park_path(@park)
    else
      render :new
    end
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to park_path(params[:park_id])
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :img_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parks_helper.rb
module ParksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parks/_form.html.erb
<%= form_with(model: park, local: true) do |form| %>
  <% if park.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(park.errors.count, "error") %> prohibited this park from being saved:</h2>

      <ul>
        <% park.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :banner_url %>
    <%= form.text_field :banner_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parks/edit.html.erb
<h1>Editing Park</h1>

<%= render 'form', park: @park %>

<%= link_to 'Show', @park %> |
<%= link_to 'Back', parks_path %>

app/views/parks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Banner url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parks.each do |park| %>
      <tr>
        <td><%= park.name %></td>
        <td><%= park.banner_url %></td>
        <td><%= link_to 'Show', park %></td>
        <td><%= link_to 'Edit', edit_park_path(park) %></td>
        <td><%= link_to 'Destroy', park, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Park', new_park_path %>

app/views/parks/new.html.erb
<h1>New Park</h1>

<%= render 'form', park: @park %>

<%= link_to 'Back', parks_path %>

app/views/parks/show.html.erb
<div class="banner" style="background: url('<%= @park.banner_url %>'); background-position: center; background-size: cover;">

</div>
<% @park.plants.each do |plant| %>
  <div class="card">
    <div class="img-card" style="background: url('<%= plant.img_url %>'); background-position: center; background-size: cover;">

    </div>
    <div>
      <h2><%= plant.name %></h2>
    </div>

    <%= link_to 'X', park_plant_path(@park, plant), method: :delete  %>
  </div>

<% end %>


<%= link_to 'add Plant', new_park_plant_path(@park) %> |
<%= link_to 'Edit', edit_park_path(@park) %> |
<%= link_to 'Back', parks_path %>

app/views/plants/new.html.erb
<h1>create plants</h1>


<%= simple_form_for([@park, @plant]) do |f| %>
  <%= f.input :name %>
  <%= f.input :img_url %>
  <%= f.submit %>
<% end %>